<?php

namespace ContainerYplCT2U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2sr1YGDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2sr1YGD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2sr1YGD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\TemoignagesController::show' => ['privates', '.service_locator.rCIedf_', 'get_ServiceLocator_RCIedfService', true],
            'App\\Controller\\UserController::add' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\VehiculesController::showVehicule' => ['privates', '.service_locator.MvsaeAz', 'get_ServiceLocator_MvsaeAzService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\TemoignagesController:show' => ['privates', '.service_locator.rCIedf_', 'get_ServiceLocator_RCIedfService', true],
            'App\\Controller\\UserController:add' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.bYqs9Eo', 'get_ServiceLocator_BYqs9EoService', true],
            'App\\Controller\\VehiculesController:showVehicule' => ['privates', '.service_locator.MvsaeAz', 'get_ServiceLocator_MvsaeAzService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\TemoignagesController::show' => '?',
            'App\\Controller\\UserController::add' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Controller\\VehiculesController::showVehicule' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\TemoignagesController:show' => '?',
            'App\\Controller\\UserController:add' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Controller\\VehiculesController:showVehicule' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
