<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Garage extends \App\Entity\Garage implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'CreatedAt' => [parent::class, 'CreatedAt', null],
        "\0".parent::class."\0".'Description' => [parent::class, 'Description', null],
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null],
        "\0".parent::class."\0".'UpdatedAt' => [parent::class, 'UpdatedAt', null],
        "\0".parent::class."\0".'amOpeningTime' => [parent::class, 'amOpeningTime', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'pmOpeningTime' => [parent::class, 'pmOpeningTime', null],
        "\0".parent::class."\0".'services' => [parent::class, 'services', null],
        "\0".parent::class."\0".'temoignages' => [parent::class, 'temoignages', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'CreatedAt' => [parent::class, 'CreatedAt', null],
        'Description' => [parent::class, 'Description', null],
        'Name' => [parent::class, 'Name', null],
        'UpdatedAt' => [parent::class, 'UpdatedAt', null],
        'amOpeningTime' => [parent::class, 'amOpeningTime', null],
        'id' => [parent::class, 'id', null],
        'pmOpeningTime' => [parent::class, 'pmOpeningTime', null],
        'services' => [parent::class, 'services', null],
        'temoignages' => [parent::class, 'temoignages', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
